name: 🐞 Bug Report 🐛
description: File a bug report
title: '[bug]: '
labels: ['potential bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!

        Do you need some help?
        ======================
        The issue tracker is meant for feature requests and bug reports only. This isn't the best place for
        support or usage questions. Questions here don't have as much visibility as they do elsewhere. Before
        you ask a question, here are some resources to get help first:

        - [Read the docs](https://react-spring.io)
        - [Explore examples](https://github.com/pmndrs/reat-spring/tree/main/demo/src/sandbox)
        - Look for/ask questions on [Stack Overflow](https://stackoverflow.com/questions/ask?tags=react-spring)
        - Ask in [GitHub Discussions](https://github.com/pmndrs/react-spring/discussions)
        - Ask in [discord](https://discord.gg/ZZjjNvJ)

        ### Test Case Starter:
        https://codesandbox.io/s/react-spring-bug-report-vbhrr
  - type: checkboxes
    id: packages
    attributes:
      label: Which react-spring target are you using?
      options:
        - label: '`@react-spring/web`'
        - label: '`@react-spring/three`'
        - label: '`@react-spring/native`'
        - label: '`@react-spring/konva`'
        - label: '`@react-spring/zdog`'
  - type: input
    attributes:
      label: What version of react-spring are you using?
    validations:
      required: true
  - type: textarea
    attributes:
      label: "What's Wrong?"
      description: A concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What you expected to happen
    validations:
      required: true
  - type: input
    attributes:
      label: Link to repo
      description: This is highly encouraged, provide either a Codesandbox demo or Github Repo
    validations:
      required: true
