export default [
  {
    name: 'parallaxvert',
    title: 'Vertical Parallax',
    description: 'Using addons/parallax to create vertical parallax layers.',
    link: '#',
  },
  {
    name: 'parallax',
    title: 'Horizontal Parallax',
    description: 'Using addons/parallax to create horizontal parallax layers.',
    link: '#',
  },
  {
    name: 'transitions',
    title: 'Transitions',
    description: 'Using transitions.',
    link: '#',
  },
  {
    name: 'nativespring',
    title: 'Native springs',
    description: 'Using the native flag for faster performance.',
    link: '#',
  },
  {
    name: 'areas',
    title: 'D3 areas',
    description: 'Using VX and D3.',
    link: '#',
  },
  {
    name: 'trails',
    title: 'Trails',
    description: 'Using trails and the reverse flag.',
    link: '#',
  },
  {
    name: 'pagetransitions',
    title: 'Simple Page transitions',
    description: 'Switching between pages using transitions.',
    link: '#',
  },
  {
    name: 'reveals',
    title: 'Simple reveals',
    description: 'Toggling objects using transitions.',
    link: '#',
  },
  {
    name: 'gestures',
    title: 'Gestures',
    description: 'Combining springs and gestures.',
    link: '#',
  },
  {
    name: 'timing',
    title: 'Scripted keyframes',
    description: 'Using functions to script animations.',
    link: '#',
  },
  {
    name: 'spring',
    title: 'Simple spring',
    description: 'Basic animations using spring.',
    link: '#',
  },
  {
    name: 'tree',
    title: 'D3 Tree view',
    description: 'Using VX and transitions.',
    link: '#',
  },
  {
    name: 'grid',
    title: 'Grid view',
    description: 'Using transitions and trails',
    link: '#',
  },
  {
    name: 'list',
    title: 'List re-ordering',
    description: 'Using transitions.',
    link: '#',
  },
  {
    name: 'morph',
    title: 'SVG morphing',
    description: 'Using flubber and springs.',
    link: '#',
  },
  {
    name: 'sunburst',
    title: 'D3 sunburst',
    description: 'Using VX and springs',
    link: '#',
  },
  {
    name: 'onrest',
    title: 'Onrest',
    description: 'Using onRest in react-spring.',
    link: '#',
  },
  {
    name: 'treeview',
    title: 'Tree view',
    description: 'Collapsable tree views using springs',
    link: '#',
  },
  {
    name: 'keyframes',
    title: 'Panel Keyframes',
    description: 'Using keyframes.',
    link: '#',
  },
  {
    name: 'script',
    title: 'Scripted keyframes',
    description: 'Using functional keyframes to controll animations.',
    link: '#',
  },
  {
    name: 'auto',
    title: 'Auto',
    description: 'Animating height: auto using springs.',
    link: '#',
  },
  {
    name: 'router',
    title: 'react-router',
    description: 'Using react-router and transitions.',
    link: '#',
  },
  {
    name: 'scroll',
    title: 'animating scroll',
    description: 'Animating scrollTop/left using springs.',
    link: '#',
  },
  {
    name: 'dashoffset',
    title: 'SVG dashOffset',
    description: 'Animate dash using springs.',
    link: '#',
  },
  {
    name: 'transitiongroup',
    title: 'Multistage transitions',
    description: 'Using transitions.',
    link: '#',
  },
  {
    name: 'chat',
    title: 'Chat',
    description: 'Whatsapp-like chat-bubbles using transitions.',
    link: '#',
  },
  {
    name: 'messages',
    title: 'Notifications',
    description: 'Basic notification-hub using springs.',
    link: '#',
  },
]