export default [
  {
    name: 'parallaxvert',
    title: 'Vertical Parallax',
    link: '#',
    tags: ['parallax'],
  },
  {
    name: 'parallax',
    title: 'Horizontal Parallax',
    link: '#',
    tags: ['parallax'],
  },
  {
    name: 'transitions',
    title: 'Transitions',
    link: '#',
    tags: ['transitions'],
  },
  {
    name: 'nativespring',
    title: 'Native springs',
    link: '#',
    tags: ['native', 'springs'],
  },
  {
    name: 'areas',
    title: 'D3 areas',
    link: '#',
    tags: ['vx', 'd3', 'transitions'],
  },
  {
    name: 'trails',
    title: 'Trails',
    link: '#',
    tags: ['trails'],
  },
  {
    name: 'pagetransitions',
    title: 'Simple Page transitions',
    link: '#',
    tags: ['transitions'],
  },
  {
    name: 'reveals',
    title: 'Simple reveals',
    link: '#',
    tags: ['transitions'],
  },
  {
    name: 'gestures',
    title: 'Gestures',
    link: '#',
    tags: ['springs', 'gestures'],
  },
  {
    name: 'timing',
    title: 'Scripted keyframes',
    link: '#',
    tags: ['keyframes'],
  },
  {
    name: 'simple-spring',
    title: 'Simple spring',
    link: '#',
    tags: ['springs'],
  },
  {
    name: 'tree',
    title: 'D3 Tree view',
    link: '#',
    tags: ['d3', 'vx', 'transitions'],
  },
  {
    name: 'grid',
    title: 'Grid view',
    link: '#',
    tags: ['transitions', 'trails'],
  },
  {
    name: 'list',
    title: 'List re-ordering',
    link: '#',
    tags: ['transitions'],
  },
  {
    name: 'morph',
    title: 'SVG morphing',
    link: '#',
    tags: ['flubber', 'svg', 'springs'],
  },
  {
    name: 'sunburst',
    title: 'D3 sunburst',
    link: '#',
    tags: ['d3', 'vx', 'springs'],
  },
  {
    name: 'onrest',
    title: 'Onrest',
    link: '#',
    tags: ['springs'],
  },
  {
    name: 'treeview',
    title: 'Tree view',
    link: '#',
    tags: ['springs'],
  },
  {
    name: 'keyframes',
    title: 'Panel Keyframes',
    link: '#',
    tags: ['keyframes', 'springs', 'trails'],
  },
  {
    name: 'script',
    title: 'Scripted keyframes',
    link: '#',
    tags: ['keyframes'],
  },
  {
    name: 'auto',
    title: 'Auto',
    link: '#',
    tags: ['springs', 'auto'],
  },
  {
    name: 'router',
    title: 'react-router',
    link: '#',
    tags: ['react-router', 'transitions'],
  },
  {
    name: 'scroll',
    title: 'animating scroll',
    link: '#',
    tags: ['springs', 'scroll'],
  },
  {
    name: 'dashoffset',
    title: 'SVG dashOffset',
    link: '#',
    tags: ['SVG', 'springs'],
  },
  {
    name: 'transitiongroup',
    title: 'Multistage transitions',
    link: '#',
    tags: ['transitions'],
  },
  {
    name: 'chat',
    title: 'Chat',
    link: '#',
    tags: ['transitions'],
  },
  {
    name: 'messages',
    title: 'Notifications',
    link: '#',
    tags: ['transitions'],
  },
]
