import { createThemeContract } from '@vanilla-extract/css'

export const vars = createThemeContract({
  colors: {
    red120: '',
    red100: '',
    red80: '',
    red60: '',
    red40: '',
    red20: '',
    steel120: '',
    steel100: '',
    steel80: '',
    steel60: '',
    steel40: '',
    steel20: '',
    white: '',
    white80: '',
    white0: '',
    black: '',
    blue: '',
    green: '',
    codeBackground: '',
    'red-outline': '',
    redYellowGradient100: '',
    redYellowGradient40: '',
    blueGreenGradient100: '',
    blueGreenGradient40: '',
  },
  shadows: {
    'red-outline': '',
  },
  space: {
    '5': '',
    '10': '',
    '15': '',
    '20': '',
    '25': '',
    '30': '',
    '35': '',
    '40': '',
    '45': '',
    '50': '',
    '60': '',
    '80': '',
    '100': '',
    '110': '',
  },
  sizes: {
    splash: '',
    type: '',
    document: '',
    largeDoc: '',
  },
  radii: {
    r4: '',
    r8: '',
    r20: '',
    round: '',
  },
  zIndices: {
    1: '',
    '1.5': '',
    2: '',
    3: '',
    4: '',
    max: '',
  },
  fonts: {
    sans: '',
    'sans-var': '',
    mono: '',
  },
  fontWeights: {
    default: '',
    bold: '',
    semiblack: '',
  },
  fontSizes: {
    XXL: '',
    XL: '',
    L: '',
    M: '',
    S: '',
    XS: '',
    XXS: '',
    code: '',
  },
  lineHeights: {
    XXL: '',
    XL: '',
    L: '',
    M: '',
    S: '',
    XS: '',
    XXS: '',
    code: '',
  },
})
