name: Bundle-size

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  size:
    name: 'Bundle Size'
    if: github.repository == 'pmndrs/react-spring'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup
        with:
          turbo-cache: 'true'

      - name: Build packages
        run: pnpm build --filter=!@react-spring/docs

      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: '{**/dist/**/*.{mjs,js},packages/types/*.{js,d.ts}}'
