name: Checks

on:
  push:
    branches:
      - 'main'
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  checks:
    name: 'Style Checks'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format:check
